name: ledger_nano
description: A Ledger App Plugin for Nano
version: 0.0.1
repository: https://github.com/cake-tech/ledger-nano

environment:
  sdk: ^3.0.6
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.1
  http: ^1.1.0
  ledger_flutter: ^1.0.1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
